// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LandingpageprojectDocumentDataSlicesSlice = MainContentSlice;

/**
 * Content for landingpageproject documents
 */
interface LandingpageprojectDocumentData {
  /**
   * Slice Zone field in *landingpageproject*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpageproject.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingpageprojectDocumentDataSlicesSlice> /**
   * Meta Description field in *landingpageproject*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landingpageproject.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *landingpageproject*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpageproject.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *landingpageproject*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landingpageproject.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * landingpageproject document from Prismic
 *
 * - **API ID**: `landingpageproject`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageprojectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingpageprojectDocumentData>,
    "landingpageproject",
    Lang
  >;

type ProjectDocumentDataSlicesSlice = ProjectDataSlice;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

type ProjectcustomDocumentDataSlicesSlice = never;

/**
 * Content for ProjectCustom documents
 */
interface ProjectcustomDocumentData {
  /**
   * `slices` field in *ProjectCustom*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projectcustom.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectcustomDocumentDataSlicesSlice>;
}

/**
 * ProjectCustom document from Prismic
 *
 * - **API ID**: `projectcustom`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectcustomDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectcustomDocumentData>,
    "projectcustom",
    Lang
  >;

export type AllDocumentTypes =
  | LandingpageprojectDocument
  | ProjectDocument
  | ProjectcustomDocument;

/**
 * Primary content in *MainContent → Default → Primary*
 */
export interface MainContentSliceDefaultPrimary {
  /**
   * projectImage field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.projectimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectimage: prismic.ImageField<never>;

  /**
   * summarizedDescription field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.summarizeddescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summarizeddescription: prismic.RichTextField;

  /**
   * Title field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * github field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.LinkField;

  /**
   * websiteUrl field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * portfolioUrl field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.portfoliourl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  portfoliourl: prismic.LinkField;

  /**
   * placement field in *MainContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_content.default.primary.placement
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placement: prismic.KeyTextField;
}

/**
 * Default variation for MainContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainContent*
 */
type MainContentSliceVariation = MainContentSliceDefault;

/**
 * MainContent Shared Slice
 *
 * - **API ID**: `main_content`
 * - **Description**: MainContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainContentSlice = prismic.SharedSlice<
  "main_content",
  MainContentSliceVariation
>;

/**
 * Primary content in *ProjectData → Default → Primary*
 */
export interface ProjectDataSliceDefaultPrimary {
  /**
   * projectImage field in *ProjectData → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_data.default.primary.projectImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectImage: prismic.ImageField<never>;

  /**
   * Description field in *ProjectData → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_data.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Title field in *ProjectData → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_data.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ProjectData Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectDataSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectDataSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectData*
 */
type ProjectDataSliceVariation = ProjectDataSliceDefault;

/**
 * ProjectData Shared Slice
 *
 * - **API ID**: `project_data`
 * - **Description**: ProjectData
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectDataSlice = prismic.SharedSlice<
  "project_data",
  ProjectDataSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LandingpageprojectDocument,
      LandingpageprojectDocumentData,
      LandingpageprojectDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectcustomDocument,
      ProjectcustomDocumentData,
      ProjectcustomDocumentDataSlicesSlice,
      AllDocumentTypes,
      MainContentSlice,
      MainContentSliceDefaultPrimary,
      MainContentSliceVariation,
      MainContentSliceDefault,
      ProjectDataSlice,
      ProjectDataSliceDefaultPrimary,
      ProjectDataSliceVariation,
      ProjectDataSliceDefault,
    };
  }
}
