// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  main_content: dynamic(() => import("./MainContent")),
  project_data: dynamic(() => import("./ProjectData")),
};
